pipeline:
  helm_dry_run:
    image: publicintegrity/drone-helm
    chart: ./charts/datashare
    release: datashare
    secrets: [ data_source_url ]
    values: image.repository=icij/datashare,image.tag=4.12.4,dataSourceUrl=$${DATA_SOURCE_URL}
    prefix: 
    dry_run: true
    namespace: datashare
    secrets: [ api_server, kubernetes_token ]
    skip_tls_verify: true
    when:
      event: [push, tag]

  helm_deploy:
    image: publicintegrity/drone-helm
    chart: ./charts/datashare
    release: datashare
    secrets: [ data_source_url ]
    values: image.repository=icij/datashare,image.tag=4.12.4,dataSourceUrl=$${DATA_SOURCE_URL}
    prefix: 
    namespace: datashare
    secrets: [ api_server, kubernetes_token ]
    skip_tls_verify: true
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
