# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: icij/datashare
  tag: 2.0.0
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
ingress:
  enabled: true
basedomain: apps.fivetwentyseven.com
env:
  DS_JAVA_OPTS: -Xmx1024m
persistence:
  accessMode: ReadWriteOnce
  size: 20Gi
elasticsearchAddress: "http://datashare-master.datashare:9200"
redisAddress: "redis://datashare-redis-master.datashare:6379"
messageBusAddress: "datashare-redis-master.datashare"
dataSourceUrl: "jdbc:postgresql://postgresql/test?user=test&password=test"

elasticsearch:
  clusterName: datashare
  imageTag: 6.3.0
  esMajorVersion: 6

redis:
  usePassword: false
  cluster:
    enabled: false
