apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        args: 
          - "--elasticsearchAddress"
          - "{{ .Values.elasticsearchAddress }}"
          - "--redisAddress"
          - "{{ .Values.redisAddress }}"
          - "--messageBusAddress"
          - "{{ .Values.messageBusAddress }}"
          - "--dataSourceUrl"
          - "{{ .Values.dataSourceUrl }}"
        volumeMounts:
          - mountPath: "/home/datashare/data"
            name: storage-volume
        env:
          {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
            - name: DS_DOCKER_MOUNTED_DATA_DIR
              value: /data
        resources:
{{ toYaml .Values.resources | indent 12 }}
