{{- if and ( .Values.ingress.user ) ( .Values.ingress.password ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-auth
data:
  auth: {{ printf "%s:%s\n" .Values.ingress.user .Values.ingress.password | b64enc | quote }}
{{- end }}
